name: Gomoku

on:
  push:
    branches-ignore:
      - 'ga-ignore-**'
  pull_request:
    branches-ignore:
      - 'ga-ignore-**'

env:
  MIRROR_URL: "git@github.com:EpitechPromo2027/B-AIA-500-NAN-5-1-gomoku-thomas.rochefeuille.git"
  DEPLOY_DOC: "TiluWeb/GomokuDoc"
  EXECUTABLES: pbrain-gomoku-ai

jobs:
  run_tests:
    runs-on: ubuntu-latest
    container:
      image: epitechcontent/epitest-docker:latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Execute the tests
        run: make tests_run

  generate_doc:
    if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          submodules: "true"

      - name: Generate Doxygen Documentation
        uses: mattnotmitt/doxygen-action@v1.9.5
        with:
          doxyfile-path: 'docs/Doxyfile'

      - name: Deploy to external github branch
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          deploy_key: ${{ secrets.GIT_SSH_PRIVATE_KEY }}
          external_repository: ${{ env.DEPLOY_DOC }}
          publish_dir: ./docs
          publish_branch: Gomoku-documentation
          exclude_assets: |
            .gitignore
            .nojekyll

  push_to_mirror:
    runs-on: ubuntu-latest
    if: github.event_name == 'push'
    needs:
      - generate_doc
      - run_tests
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: pixta-dev/repository-mirroring-action@v1
        with:
          target_repo_url: ${{ env.MIRROR_URL }}
          ssh_private_key:
            ${{ secrets.GIT_SSH_PRIVATE_KEY }}